In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('https://shelterdata.s3.amazonaws.com/shelter1000.csv')

In [2]:
df

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A794011,Chunk,05/08/2019 6:20:00 PM,May 2019,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,07/18/2018 4:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A821648,NaN,08/16/2020 11:38:00 AM,Aug 2020,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
3,A720371,Moose,02/13/2016 5:59:00 PM,Feb 2016,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
4,A674754,NaN,03/18/2014 11:47:00 AM,Mar 2014,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby
...,...,...,...,...,...,...,...,...,...,...,...,...
995,A691208,NaN,11/11/2014 6:13:00 PM,Nov 2014,12/31/2013,Adoption,NaN,Cat,Spayed Female,10 months,Domestic Shorthair Mix,Black/White
996,A718620,*Toby Sue,03/01/2016 1:53:00 PM,Mar 2016,07/23/2015,Adoption,NaN,Cat,Spayed Female,7 months,Domestic Shorthair Mix,Black/White
997,A705114,NaN,06/13/2015 3:47:00 PM,Jun 2015,06/11/2015,Transfer,Partner,Dog,Intact Male,2 days,German Shepherd Mix,Brown
998,A800888,NaN,08/01/2019 3:27:00 PM,Aug 2019,07/03/2019,Transfer,Partner,Dog,Intact Female,4 weeks,Cavalier Span,Black/White
999,A796517,Chiquis,06/08/2019 12:21:00 PM,Jun 2019,06/02/2017,Adoption,NaN,Dog,Spayed Female,2 years,Chihuahua Shorthair Mix,Brown/White

In [3]:
df["DateTime"].max()

'12/31/2016 3:54:00 PM'

In [7]:
df[['month','year']]=df['MonthYear'].str.split(' ',expand=True)

In [8]:
df

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color,month,year
0,A794011,Chunk,05/08/2019 6:20:00 PM,May 2019,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White,May,2019
1,A776359,Gizmo,07/18/2018 4:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown,Jul,2018
2,A821648,NaN,08/16/2020 11:38:00 AM,Aug 2020,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray,Aug,2020
3,A720371,Moose,02/13/2016 5:59:00 PM,Feb 2016,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff,Feb,2016
4,A674754,NaN,03/18/2014 11:47:00 AM,Mar 2014,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby,Mar,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A691208,NaN,11/11/2014 6:13:00 PM,Nov 2014,12/31/2013,Adoption,NaN,Cat,Spayed Female,10 months,Domestic Shorthair Mix,Black/White,Nov,2014
996,A718620,*Toby Sue,03/01/2016 1:53:00 PM,Mar 2016,07/23/2015,Adoption,NaN,Cat,Spayed Female,7 months,Domestic Shorthair Mix,Black/White,Mar,2016
997,A705114,NaN,06/13/2015 3:47:00 PM,Jun 2015,06/11/2015,Transfer,Partner,Dog,Intact Male,2 days,German Shepherd Mix,Brown,Jun,2015
998,A800888,NaN,08/01/2019 3:27:00 PM,Aug 2019,07/03/2019,Transfer,Partner,Dog,Intact Female,4 weeks,Cavalier Span,Black/White,Aug,2019
999,A796517,Chiquis,06/08/2019 12:21:00 PM,Jun 2019,06/02/2017,Adoption,NaN,Dog,Spayed Female,2 years,Chihuahua Shorthair Mix,Brown/White,Jun,2019

In [9]:
import numpy as np
df["sex"]=df["Sex upon Outcome"].replace("Unknown",np.nan)

In [10]:
df

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color,month,year,sex
0,A794011,Chunk,05/08/2019 6:20:00 PM,May 2019,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White,May,2019,Neutered Male
1,A776359,Gizmo,07/18/2018 4:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown,Jul,2018,Neutered Male
2,A821648,NaN,08/16/2020 11:38:00 AM,Aug 2020,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray,Aug,2020,NaN
3,A720371,Moose,02/13/2016 5:59:00 PM,Feb 2016,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff,Feb,2016,Neutered Male
4,A674754,NaN,03/18/2014 11:47:00 AM,Mar 2014,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby,Mar,2014,Intact Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A691208,NaN,11/11/2014 6:13:00 PM,Nov 2014,12/31/2013,Adoption,NaN,Cat,Spayed Female,10 months,Domestic Shorthair Mix,Black/White,Nov,2014,Spayed Female
996,A718620,*Toby Sue,03/01/2016 1:53:00 PM,Mar 2016,07/23/2015,Adoption,NaN,Cat,Spayed Female,7 months,Domestic Shorthair Mix,Black/White,Mar,2016,Spayed Female
997,A705114,NaN,06/13/2015 3:47:00 PM,Jun 2015,06/11/2015,Transfer,Partner,Dog,Intact Male,2 days,German Shepherd Mix,Brown,Jun,2015,Intact Male
998,A800888,NaN,08/01/2019 3:27:00 PM,Aug 2019,07/03/2019,Transfer,Partner,Dog,Intact Female,4 weeks,Cavalier Span,Black/White,Aug,2019,Intact Female
999,A796517,Chiquis,06/08/2019 12:21:00 PM,Jun 2019,06/02/2017,Adoption,NaN,Dog,Spayed Female,2 years,Chihuahua Shorthair Mix,Brown/White,Jun,2019,Spayed Female

In [11]:
df.drop(columns=["MonthYear","Sex upon Outcome"],inplace=True)

In [12]:
df

,Animal ID,Name,DateTime,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Age upon Outcome,Breed,Color,month,year,sex
0,A794011,Chunk,05/08/2019 6:20:00 PM,05/02/2017,Rto-Adopt,NaN,Cat,2 years,Domestic Shorthair Mix,Brown Tabby/White,May,2019,Neutered Male
1,A776359,Gizmo,07/18/2018 4:02:00 PM,07/12/2017,Adoption,NaN,Dog,1 year,Chihuahua Shorthair Mix,White/Brown,Jul,2018,Neutered Male
2,A821648,NaN,08/16/2020 11:38:00 AM,08/16/2019,Euthanasia,NaN,Other,1 year,Raccoon,Gray,Aug,2020,NaN
3,A720371,Moose,02/13/2016 5:59:00 PM,10/08/2015,Adoption,NaN,Dog,4 months,Anatol Shepherd/Labrador Retriever,Buff,Feb,2016,Neutered Male
4,A674754,NaN,03/18/2014 11:47:00 AM,03/12/2014,Transfer,Partner,Cat,6 days,Domestic Shorthair Mix,Orange Tabby,Mar,2014,Intact Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A691208,NaN,11/11/2014 6:13:00 PM,12/31/2013,Adoption,NaN,Cat,10 months,Domestic Shorthair Mix,Black/White,Nov,2014,Spayed Female
996,A718620,*Toby Sue,03/01/2016 1:53:00 PM,07/23/2015,Adoption,NaN,Cat,7 months,Domestic Shorthair Mix,Black/White,Mar,2016,Spayed Female
997,A705114,NaN,06/13/2015 3:47:00 PM,06/11/2015,Transfer,Partner,Dog,2 days,German Shepherd Mix,Brown,Jun,2015,Intact Male
998,A800888,NaN,08/01/2019 3:27:00 PM,07/03/2019,Transfer,Partner,Dog,4 weeks,Cavalier Span,Black/White,Aug,2019,Intact Female
999,A796517,Chiquis,06/08/2019 12:21:00 PM,06/02/2017,Adoption,NaN,Dog,2 years,Chihuahua Shorthair Mix,Brown/White,Jun,2019,Spayed Female

In [13]:
df.to_csv('processed_data.csv')